Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-087c17d1fe0178315
      InstanceType: t2.micro
      UserData:
        Fn::Base64:
           !Sub |
              #!/bin/bash
              sudo yum install httpd -y
              sudo service httpd start
              chkconfig httpd on
      KeyName: Cyber-Key2
  Ec2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1b
      ImageId: ami-087c17d1fe0178315
      InstanceType: t2.micro
      UserData:
        Fn::Base64:
           !Sub |
              #!/bin/bash
              sudo yum install httpd -y
              sudo service httpd start
              chkconfig httpd on
      KeyName: Cyber-Key2
Parameters:
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
